### ISSUE TITLE
 ❗️叮咚整合签到, 错误! TypeError: Cannot read properties of undefined (reading 'split')     at getUrl (/ql/scripts/justplayscript_ddxp_ddxp.js:125:23)     at /ql/scripts/justplayscript_ddxp_ddxp.js:32:17     at processTicksAndRejections (node:internal/process/task_queues:96:5)

### ISSUE THREAD

**Issue by joekleenubuntu** [justplayscript/ddxp#3]
有个东西报错。不知道是什么问题？

**Comment by justplayscript** [comment]
ddxpurl没抓取配置

**Comment by joekleenubuntu** [comment]
@justplayscript  我已经配置了这个了，两个账户有一个出现这个的
